version: '3'

services:
  allure-docker-service-ui:
    build:
      context: ../allure-docker-service-ui
      dockerfile: docker/Dockerfile
      args:
        BUILD_DATE: "na"
        VERSION: "na"
        VCS_REF: "na"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050" # <-- or any script here if ALLURE_DOCKER_PUBLIC_API_URL_IS_SCRIPT is set, example below
      #ALLURE_DOCKER_PUBLIC_API_URL: "echo http://$$(curl http://checkip.amazonaws.com)"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
      #ALLURE_DOCKER_PUBLIC_API_URL_IS_SCRIPT: 1 <-- if specified the url will be parsed as script
      #URL_PREFIX: "/my-prefix"
    ports:
      - "7474:5252"

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 12
      SECURITY_USER: my_username
      SECURITY_PASS: my_password
      SECURITY_VIEWER_USER: "view_user"
      SECURITY_VIEWER_PASS: "view_pass"
      SECURITY_ENABLED: 1
      MAKE_VIEWER_ENDPOINTS_PUBLIC: 0
      #URL_PREFIX: /my-prefix
      #ACCESS_TOKEN_EXPIRES_IN_SECONDS: 10
      #REFRESH_TOKEN_EXPIRES_IN_SECONDS: 10
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects
